server {
    listen 8080;

    root /usr/share/nginx/html;
    index index.html;

    types {
        text/html                             html htm;
        text/css                              css;
        application/javascript                js mjs;
        application/wasm                      wasm;
        image/png                             png;
        image/jpeg                            jpg jpeg;
        image/svg+xml                         svg svgz;
        application/json                      json;
        font/woff2                            woff2;
        font/woff                             woff;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
