name: player
description: "A media player for Ister"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.0+1
  oidc: ^0.12.1+2
  oidc_default_store: ^0.4.0+3
  graphql_flutter: ^5.1.2
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  skeletonizer: ^2.1.0+1
  flutter_localizations:
    sdk: flutter
  intl: any

#dependency_overrides:
#  web: ">=0.5.1 <2.0.0"
dependency_overrides:
  # Waiting for https://github.com/juliansteenbakker/flutter_secure_storage/pull/923 pr merged
  flutter_secure_storage_linux:
    git:
      url: https://github.com/m-berto/flutter_secure_storage.git
      ref: patch-2
      path: flutter_secure_storage_linux
  flutter_secure_storage_platform_interface: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  graphql_codegen: ^1.2.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/DroidSansFallback.ttf
    - assets/background.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
