import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:player/routes/AppRouter.gr.dart';

import 'support/harness.dart';

/// Reads an epub in the native reader: chapter text renders (fetched through
/// the epub resource endpoint), and scrolling syncs reading progress to the
/// server via POST /reading-progress.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('read an epub and sync reading progress', (tester) async {
    await bootApp(tester);
    await enterServerShell(tester);

    // "Winter Sleep": a plain epub without overlays AND without audiobook chapters — a book
    // with chapters (Night Flight) gets chapter-progress rows from the audiobook bridge,
    // whose location-less sync would race this test's location assertion. Comic volumes are
    // Books too (chapterless, but their "epubFiles" are cbz), so require an author: comics
    // are series-first and carry none.
    final books = await gqlRaw(
        '{ books(size: 50) { content { id name author { id } chapters { id } epubFiles { id mediaOverlays directory { node { url } } } } } }');
    final book = (books['books']['content'] as List).firstWhere(
        (b) =>
            b['author'] != null &&
            ((b['chapters'] as List? ?? []).isEmpty) &&
            (b['epubFiles'] as List? ?? []).any((f) => f['mediaOverlays'] != true),
        orElse: () => fail('no plain epub book without chapters found'));
    final bookId = book['id'] as String;
    final epubFile = (book['epubFiles'] as List)
        .firstWhere((f) => f['mediaOverlays'] != true);
    final mediaFileId = epubFile['id'] as String;
    final nodeUrl = epubFile['directory']['node']['url'] as String;

    await pushRoute(
        tester,
        ReaderRoute(
            bookId: bookId, mediaFileId: mediaFileId, nodeUrl: nodeUrl));

    // Chapter text generated by create_books.sh.
    await pumpUntil(
      tester,
      () => find
          .textContaining('first sentence', findRichText: true)
          .evaluate()
          .isNotEmpty,
      timeout: const Duration(minutes: 1),
      description: 'the chapter text to render',
    );

    // Read on to the next chapter: the tiny test chapters fit on one screen, so scrolling
    // never changes the reading block and the sync service (by design) has nothing to save.
    // A chapter jump is a guaranteed locator change — but reports are suppressed until the
    // reader finished weighing every chapter, so keep paging back and forth while polling:
    // the first jump after the weighing completes is the one that syncs.
    await pumpUntilFound(tester, find.byIcon(Icons.skip_next));

    dynamic progress;
    final deadline = DateTime.now().add(const Duration(seconds: 90));
    var iteration = 0;
    while (DateTime.now().isBefore(deadline)) {
      try {
        progress = await restGet('/reading-progress?bookId=$bookId');
        if (progress != null && progress['location'] != null) break;
      } catch (_) {
        // 404 until the first sync lands.
      }
      if (iteration % 4 == 0) {
        final icon = iteration % 8 == 0 ? Icons.skip_next : Icons.skip_previous;
        final button = find.byIcon(icon);
        if (button.evaluate().isNotEmpty) {
          await tester.tap(button, warnIfMissed: false);
        }
      }
      iteration++;
      await tester.pump(const Duration(seconds: 1));
    }
    expect(progress, isNotNull,
        reason: 'reading progress should be synced to the server');
    expect(progress['location'], isNotEmpty,
        reason: 'the synced progress should carry a reading location');
  });
}
