import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:player/routes/AppRouter.gr.dart';

import 'support/harness.dart';

/// Reads an epub in the native reader: chapter text renders (fetched through
/// the epub resource endpoint), and scrolling syncs reading progress to the
/// server via POST /reading-progress.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('read an epub and sync reading progress', (tester) async {
    await bootApp(tester);
    await enterServerShell(tester);

    // "Winter Sleep" is the plain epub without overlays in the testdata set.
    final books = await gqlRaw(
        '{ books(size: 50) { content { id name epubFiles { id mediaOverlays directory { node { url } } } } } }');
    final book = (books['books']['content'] as List).firstWhere(
        (b) => (b['epubFiles'] as List? ?? [])
            .any((f) => f['mediaOverlays'] != true),
        orElse: () => fail('no plain epub book found'));
    final bookId = book['id'] as String;
    final epubFile = (book['epubFiles'] as List)
        .firstWhere((f) => f['mediaOverlays'] != true);
    final mediaFileId = epubFile['id'] as String;
    final nodeUrl = epubFile['directory']['node']['url'] as String;

    await pushRoute(
        tester,
        ReaderRoute(
            bookId: bookId, mediaFileId: mediaFileId, nodeUrl: nodeUrl));

    // Chapter text generated by create_books.sh.
    await pumpUntil(
      tester,
      () => find
          .textContaining('first sentence', findRichText: true)
          .evaluate()
          .isNotEmpty,
      timeout: const Duration(minutes: 1),
      description: 'the chapter text to render',
    );

    // Read on: scroll the chapter; the sync service debounces ~1.5s then POSTs.
    await tester.drag(find.byType(Scrollable).last, const Offset(0, -600));
    await pumpUntil(tester, () => true,
        timeout: const Duration(seconds: 4), description: 'progress debounce');

    // Scroll again periodically while polling: on a slow CI runner the first drag can land
    // before the reader restored its position, in which case no location-bearing sync goes
    // out until a later scroll. 90s because the debounce + POST + poll all share 2 cores.
    dynamic progress;
    final deadline = DateTime.now().add(const Duration(seconds: 90));
    var iteration = 0;
    while (DateTime.now().isBefore(deadline)) {
      try {
        progress = await restGet('/reading-progress?bookId=$bookId');
        if (progress != null && progress['location'] != null) break;
      } catch (_) {
        // 404 until the first sync lands.
      }
      if (iteration++ % 5 == 4) {
        await tester.drag(find.byType(Scrollable).last, const Offset(0, -200));
      }
      await tester.pump(const Duration(seconds: 1));
    }
    expect(progress, isNotNull,
        reason: 'reading progress should be synced to the server');
    expect(progress['location'], isNotEmpty,
        reason: 'the synced progress should carry a reading location');
  });
}
