query recentlyWatched($libraryId: ID) {
    recentlyWatched(libraryId: $libraryId) {
        type
        episode {
            id
            number
            show { id metadata { ...fragmentMetadata } images { ...fragmentImages } }
            season { number }
            watchStatus { id playQueueItemId progressInMilliseconds watched }
            mediaFile { id durationInMilliseconds }
            metadata { ...fragmentMetadata }
            images { ...fragmentImages }
        }
        movie {
            id
            name
            images { ...fragmentImages }
            metadata { ...fragmentMetadata }
            watchStatus { id playQueueItemId progressInMilliseconds watched }
            mediaFile { id durationInMilliseconds }
        }
        chapter {
            id
            number
            book {
                id name title
                images { ...fragmentImages }
                metadata { ...fragmentMetadata }
                progress { ...fragmentBookProgress }
            }
            metadata { ...fragmentMetadata }
            watchStatus { id playQueueItemId progressInMilliseconds watched }
            mediaFile { id durationInMilliseconds }
        }
        book {
            id
            name
            title
            series { id name }
            images { ...fragmentImages }
            metadata { ...fragmentMetadata }
            watchStatus { id watched readingLocation readingProgress }
            progress { ...fragmentBookProgress }
            epubFiles { id path format mediaOverlays directory { node { url } } }
        }
        podcastEpisode {
            id
            publishedAt
            podcast { id title images { ...fragmentImages } }
            metadata { ...fragmentMetadata }
            watchStatus { id playQueueItemId progressInMilliseconds watched }
            mediaFile { id durationInMilliseconds }
        }
    }
}
