query movies($page: Int, $size: Int, $sorting: SortingEnum, $sortingOrder: SortingOrder, $libraryId: ID, $filter: MediaFilterInput) {
    movies(page: $page, size: $size, sorting: $sorting, sortingOrder: $sortingOrder, libraryId: $libraryId, filter: $filter) {
        number
        size
        totalElements
        totalPages
        content {
            id
            name
            releaseYear
            images { ...fragmentImages }
            metadata { ...fragmentMetadata }
        }
    }
}
