query showById($id: ID!) {
    showById(id: $id) {
        id
        images {
            ...fragmentImages
        }
        name
        releaseYear
        metadata {
            ...fragmentMetadata
        }
        seasons {
            id
            number
        }
        cast {
            ...fragmentCastMember
        }
        rating
        tmdbId
        imdbId
        voteAverage
        voteCount
        contentRating
        status
        homepage
        networks
        studios
        originCountry
        keywords
        trailerKey
        trailerSite
    }
}
