query shows($page: Int, $size: Int, $sorting: SortingEnum, $sortingOrder: SortingOrder, $libraryId: ID, $filter: MediaFilterInput) {
    shows(page: $page, size: $size, sorting: $sorting, sortingOrder: $sortingOrder, libraryId: $libraryId, filter: $filter) {
        number
        size
        totalElements
        totalPages
        content {
            id
            releaseYear
            name
            images {
                ...fragmentImages
            }
            episodes {
                number
            }
            metadata {
                ...fragmentMetadata
            }

        }
    }
}
