mutation updatePlayQueue($id: ID!, $playQueueItemId: ID!, $progressInMilliseconds: Int!, $streamSettings: StreamSettingsInput, $playState: PlayState, $deviceId: ID, $anchorPositionMs: Int, $anchorServerTimeMs: Float, $repeatMode: RepeatMode) {
    updatePlayQueue(id: $id, playQueueItemId: $playQueueItemId, progressInMilliseconds: $progressInMilliseconds, streamSettings: $streamSettings, playState: $playState, deviceId: $deviceId, anchorPositionMs: $anchorPositionMs, anchorServerTimeMs: $anchorServerTimeMs, repeatMode: $repeatMode) {
        ...fragmentPlayQueue
    }
}
